---
- hosts: all
  become: yes
  tasks:
    # Paso 1: Actualizar repositorios y paquetes del sistema
    - name: Actualizar repositorios y paquetes del sistema
      apt:
        update_cache: yes
        upgrade: dist

    # Paso 2: Configurar locales a es_ES.UTF-8
    - name: Configurar locales a es_ES.UTF-8
      shell: |
        sudo locale-gen es_ES.UTF-8
        sudo update-locale LANG=es_ES.UTF-8

    # Paso 3: Configurar zona horaria a Europe/Madrid
    - name: Configurar la zona horaria a Europe/Madrid
      command: timedatectl set-timezone Europe/Madrid

    # Paso 4: Instalar NTP para la sincronización de la hora
    - name: Instalar NTP para sincronización de hora
      apt:
        name: ntp
        state: present

    # Paso 5: Instalar Postgres 12
    - name: Instalar repositorios de Postgres y Postgres 12
      shell: |
        sudo apt install -y postgresql-common
        sudo /usr/share/postgresql-common/pgdg/apt.postgresql.org.sh
        sudo apt install -y postgresql-12

    # Paso 6: Asignar nombre de dominio en /etc/hosts
    - name: Asignar nombre de dominio en /etc/hosts
      lineinfile:
        path: /etc/hosts
        line: "127.0.1.1       ejemplo.zataca.com  ISPConfig"
        create: yes

    # Paso 7: Reiniciar el equipo para aplicar el nombre de dominio
    - name: Reiniciar el equipo para aplicar el nombre de dominio
      reboot:
        msg: "Reiniciando el equipo para aplicar el nombre de dominio."
        connect_timeout: 5
        reboot_timeout: 600
      ignore_errors: yes

    # Paso 8: Instalar UFW si no está presente
    - name: Instalar UFW si no está presente
      apt:
        name: ufw
        state: present

    # Paso 9: Crear el directorio /run/sshd si no existe
    - name: Crear el directorio /run/sshd si no existe
      file:
        path: /run/sshd
        state: directory
        mode: '0755'

    # Paso 10: Asegurar que DebianBanner no esté dentro del bloque Match
    - name: Asegurar que DebianBanner no esté dentro del bloque Match
      lineinfile:
        path: /etc/ssh/sshd_config
        insertafter: '^# override default of no subsystems'
        line: 'DebianBanner no'
        state: present

    # Paso 11: Configurar SSH para permitir solo conexiones desde la red 192.168.0.0/24
    - name: Configurar SSH para permitir solo conexiones desde la red 192.168.0.0/24
      blockinfile:
        path: /etc/ssh/sshd_config
        block: |
          Match Address 192.168.0.0/24
          PermitRootLogin yes
          PasswordAuthentication yes

    # Paso 12: Reiniciar el servicio SSH para aplicar cambios
    - name: Reiniciar el servicio SSH para aplicar cambios
      systemd:
        name: ssh
        state: restarted

    # Paso 13: Generar certificado SSL para Pure-FTPd
    - name: Generar certificado SSL para Pure-FTPd en /tmp
      shell: |
        openssl req -x509 -nodes -days 7300 -newkey rsa:2048 \
        -subj '/C=DE/ST=None/L=None/O=IT/CN=prueba.myguest.virtualbox.org' \
        -keyout /tmp/pure-ftpd.pem -out /tmp/pure-ftpd.pem
      register: cert_creation_result
      ignore_errors: yes

    # Paso 14: Mover certificado Pure-FTPd a /etc/ssl/private/
    - name: Mover certificado Pure-FTPd a /etc/ssl/private/
      command: mv /tmp/pure-ftpd.pem /etc/ssl/private/pure-ftpd.pem
      when: cert_creation_result is succeeded

    # Paso 15: Ajustar permisos del certificado Pure-FTPd
    - name: Ajustar permisos del certificado Pure-FTPd en /etc/ssl/private/
      file:
        path: /etc/ssl/private/pure-ftpd.pem
        owner: root
        group: root
        mode: '0600'
      when: cert_creation_result is succeeded

    # Paso 16: Descargar e instalar ISPConfig con Nginx
    - name: Descargar e instalar ISPConfig con Nginx
      shell: |
        wget -O - https://get.ispconfig.org | sudo sh -s -- --use-nginx --use-ftp-ports=40110-40210 --unattended-upgrades --i-know-what-i-am-doing
      register: install_ispconfig_result

    # Paso 17: Mostrar las contraseñas de ISPConfig
    - name: Mostrar contraseñas de ISPConfig
      shell: |
        grep -E "(Your ISPConfig admin password is|Your MySQL root password is)" /tmp/ispconfig-ai/var/log/setup-*
      register: ispconfig_passwords_output

    - name: Mostrar contraseñas en el log de Ansible
      debug:
        msg: "{{ ispconfig_passwords_output.stdout }}"

    # Paso 18: Eliminar ficheros de instalación temporales de ISPConfig
    - name: Eliminar ficheros de instalación temporales de ISPConfig
      file:
        path: /tmp/ispconfig-ai/var/log/setup-*
        state: absent
      when: install_ispconfig_result is succeeded

    # Paso 19: Configurar Nginx para ocultar tokens del servidor
    - name: Configurar Nginx para ocultar tokens del servidor
      lineinfile:
        path: /etc/nginx/nginx.conf
        insertafter: '^http {'
        line: '    server_tokens off;'
      notify:
        - Restart nginx

    # Paso 20: Eliminar la web por defecto de Nginx
    - name: Eliminar la web por defecto de Nginx
      lineinfile:
        path: /var/www/html/index.nginx-debian.html
        create: yes
        line: ""

    # Paso 21: Instalar paquetes necesarios para facturas en PDF
    - name: Instalar paquetes para imprimir facturas en PDF
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - chromium-browser
        - libnss3
        - libatk1.0-0
        - libatk-bridge2.0-0
        # (añadir los demás paquetes que mencionaste en tu lista)

    # Paso 22: Instalar Yarn
    - name: Instalar Yarn
      shell: |
        curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo gpg --dearmor -o /usr/share/keyrings/yarnkey.gpg
        echo "deb [signed-by=/usr/share/keyrings/yarnkey.gpg] https://dl.yarnpkg.com/debian stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
        sudo apt update && sudo apt install yarn

    # Paso 23: Instalar PHP Postgres y bcmath
    - name: Instalar drivers Postgres y bcmath de PHP
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - php8.2-pgsql
        - php7.4-bcmath
        # (añadir las demás versiones que mencionaste)

    # Paso 24: Instalar supervisord
    - name: Instalar supervisord
      apt:
        name: supervisor
        state: present

    # Paso 25: Ejecutar auditoría de seguridad con Lynis
    - name: Auditar el sistema con Lynis
      shell: |
        cd /root
        git clone https://github.com/CISOfy/lynis
        cd lynis
        ./lynis audit system -Q

  handlers:
    - name: Restart sshd
      systemd:
        name: ssh
        state: restarted

    - name: Restart nginx
      systemd:
        name: nginx
        state: restarted

    - name: Restart postfix
      systemd:
        name: postfix
        state: restarted

    - name: Restart dovecot
      systemd:
        name: dovecot
        state: restarted
