---
- hosts: all
  become: yes
  tasks:
    # Paso 1: Actualizar repositorios y paquetes del sistema
    - name: Actualizar repositorios y paquetes del sistema
      apt:
        update_cache: yes
        upgrade: dist

    # Paso 2: Instalar el agente Zabbix
    - name: Instalar Zabbix Agent
      apt:
        name: zabbix-agent
        state: present

    # Paso 3: Generar PSK para Zabbix Agent
    - name: Generar archivo PSK para Zabbix
      shell: openssl rand -hex 32 > /etc/zabbix/zabbix_secret.psk

    # Paso 4: Ajustar permisos del archivo PSK
    - name: Ajustar permisos del archivo PSK
      file:
        path: /etc/zabbix/zabbix_secret.psk
        owner: zabbix
        group: zabbix
        mode: '0640'

    # Paso 5: Configurar Zabbix Agent
    - name: Configurar Zabbix Agent con PSK
      lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      loop:
        - { regexp: '^Server=', line: 'Server=192.168.0.149' }
        - { regexp: '^ServerActive=', line: 'ServerActive=192.168.0.149' }
        - { regexp: '^# HostnameItem=system.hostname', line: 'HostnameItem=system.hostname' }
        - { regexp: '^Hostname=', line: 'Hostname={{ inventory_hostname }}' }
        - { regexp: '^# TLSConnect=', line: 'TLSConnect=psk' }
        - { regexp: '^# TLSAccept=', line: 'TLSAccept=psk' }
        - { regexp: '^# TLSPSKIdentity=', line: 'TLSPSKIdentity={{ inventory_hostname }}' }
        - { regexp: '^# TLSPSKFile=', line: 'TLSPSKFile=/etc/zabbix/zabbix_secret.psk' }

    # Paso 6: Reiniciar el servicio Zabbix Agent
    - name: Reiniciar Zabbix Agent para aplicar cambios
      systemd:
        name: zabbix-agent
        state: restarted

    # Paso 7: Leer el archivo PSK y mostrarlo
    - name: Obtener el contenido del PSK generado
      slurp:
        src: /etc/zabbix/zabbix_secret.psk
      register: psk_content

    - name: Mostrar el PSK en el log de Ansible
      debug:
        msg: "PSK generado: {{ psk_content['content'] | b64decode }}"
