---
- hosts: all
  become: yes
  tasks:
    # Paso 1: Actualizar repositorios y paquetes del sistema
    - name: Actualizar repositorios y paquetes del sistema
      apt:
        update_cache: yes
        upgrade: dist

    # Paso 2: Instalar Zabbix Agent
    - name: Instalar Zabbix Agent
      apt:
        name: zabbix-agent
        state: present

    # Paso 3: Generar archivo PSK para Zabbix
    - name: Generar archivo PSK para Zabbix
      command: "openssl rand -hex 64 > /etc/zabbix/encrypt.psk"
      register: psk_result

    # Paso 4: Mover archivo PSK a la ubicación correcta y ajustar permisos
    - name: Mover archivo PSK a la ubicación correcta
      command: mv /etc/zabbix/encrypt.psk /etc/zabbix/
      ignore_errors: yes

    - name: Ajustar permisos del archivo PSK
      file:
        path: /etc/zabbix/encrypt.psk
        owner: zabbix
        group: zabbix
        mode: '0640'

    # Paso 5: Configurar Zabbix Agent con PSK
    - name: Configurar Zabbix Agent con PSK
      lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      loop:
        - { regexp: '^Server=', line: 'Server=192.168.0.149' }
        - { regexp: '^ListenPort=', line: 'ListenPort=10050' }
        - { regexp: '^ServerActive=', line: 'ServerActive=192.168.0.149' }
        - { regexp: '^Hostname=', line: 'Hostname={{ ansible_hostname }}' }
        - { regexp: '^HostnameItem=', line: 'HostnameItem=system.hostname' }
        - { regexp: '^TLSConnect=', line: 'TLSConnect=psk' }
        - { regexp: '^TLSAccept=', line: 'TLSAccept=psk' }
        - { regexp: '^TLSPSKIdentity=', line: 'TLSPSKIdentity={{ ansible_hostname }}' }
        - { regexp: '^TLSPSKFile=', line: 'TLSPSKFile=/etc/zabbix/encrypt.psk' }

    # Paso 6: Reiniciar Zabbix Agent para aplicar cambios
    - name: Reiniciar Zabbix Agent para aplicar cambios
      systemd:
        name: zabbix-agent
        state: restarted

    # Paso 7: Mostrar PSK generado en el log de Ansible
    - name: Mostrar PSK generado en el log de Ansible
      debug:
        var: psk_result.stdout

